spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - JwtAuthenticationGatewayFilter
        - id: clothes
          uri: lb://clothes
          predicates:
            - Path=/clothes/**, /cart/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**, /errorful/**
        - id: stock
          uri: lb://stock
          predicates:
            - Path=/stock/**
  data:
    redis:
      host: redis
      port: 6379

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret

