spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/user/**
          filters:
            - JwtAuthenticationGatewayFilter
        - id: clothes
          uri: http://clothes:8081
          predicates:
            - Path=/clothes/**
          filters:
            - JwtAuthenticationGatewayFilter
        - id: order
          uri: http://order:8082
          predicates:
            - Path=/order/**
          filters:
            - JwtAuthenticationGatewayFilter
  data:
    redis:
      host: localhost
      port: 6379

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret

