spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/order?
    username: root
    password: 1234
  application:
    name: order-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true #  /actuator/health 로 상태 확인 가능
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        failure-rate-threshold: 10
        slow-call-rate-threshold: 10
        slow-call-duration-threshold: 7s
        wait-duration-in-open-state: 10s # open -> half open 전환 시간
        permitted-number-of-calls-in-half-open-state: 5
    instances:
      default:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 6s
        cancelRunningFuture: true
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 500ms
